const recentProjectsData = [
    {
        title: "Solar Energy",
        information: "This 'Awesun' Solar Energy Visualiser displays the latest UK solar energy generation statistics in half-hourly increments. Peak production statistics are included for comparison, and a responsive animation to represent the strength of the sun at different times.",
        fileName: "AwesunShotBanner.png",
        url: "https://awesun-solar-visualiser.vercel.app/",

        heading1: "TECHNOLOGIES",
        value1: "React, Next JS, TypeScript, Fetch API, CSS Animations, Tailwind",
        heading2: "FEATURES",
        value2: "responsiveness, live updates, animations, daily/monthly/yearly views",
        heading3: "COLLABORATORS",
        value3: "Built in a team of 3 with GitHub used for version control.",
        heading4: "LEARNINGS",
        value4: "humility!",
    },
    {
        title: "Mathemagical",
        information: "Animating beautiful equations, and providing a trigonemetric 'make your own' graph.",
        fileName: "MathemagicalShot3.png",
        url: "https://mathemagical.vercel.app/",

        heading1: "TECHNOLOGIES",
        value1: "React, TypeScript, HTML canvas",
        heading2: "FEATURES",
        value2: "responsiveness, fast rendering, create-your-own",
        heading3: "COLLABORATORS",
        value3: "None.",
        heading4: "LEARNINGS",
        value4: "There are many ways to code the same thing, often pre-made tools are already available online.",
    },
    {
        title: "Ruby on Rails CRUD Dex",
        information: "A simple CRUD-functionality Pokedex App, which was my first project in Ruby on Rails, having worked primarily in React/Next JS thus far.",
        fileName: "RubyDexShotBannerShort.png",
        url: "https://rubyonrails-pokedex.onrender.com/pokemonsters",

        heading1: "TECHNOLOGIES",
        value1: "Ruby on Rails, CSS",
        heading2: "FEATURES",
        value2: "CRUD functionality: create, read, update, delete; resetting database",
        heading3: "COLLABORATORS",
        value3: "None.",
        heading4: "LEARNINGS",
        value4: "Once installed, Ruby on Rails has some scripts that can make project setup a breeze.",
    },
    {
        title: "Positive Homeless Shelter Database",
        information: "The application helps staff quickly record information about their service users while out in the streets or back in the shelter. It aims to help improve both service staff and service user experiences.",
        fileName: "ShelterShotsBanner.png",
        url: "https://secure-nextjs-homeless-shelter-database.vercel.app/",
        heading1: "TECHNOLOGIES",
        value1: "Next JS, Supabase (authentication), Jest (testing), SQL",
        heading2: "FEATURES",
        value2: "authentication, authorisation, testing, database-connectivity",
        heading3: "COLLABORATORS",
        value3: "Built in a team of 6 with GitHub used for version control.",
        heading4: "LEARNINGS",
        value4: "Don't spent excessive time optimising for use cases you may never need.",
    },
    {
        title: "Deployment Debugger",
        information: "This application allows me to check all of my deployments statuses (and prevent any from spinning down with activity) by visiting a single site. Python, Flask and Beautiful Soup were used to scrape my sites for their html content, and the site itself displays whether the url request was valid, and whether the html response to the request was as expected.",
        fileName: "DeploymentsDashboardShot2.png",
        url: "https://jamesdiffeycoding-pythonlivedashboard.vercel.app/",

        heading1: "TECHNOLOGIES",
        value1: "Python, Flask, BeautifulSoup (web scraper) HTML, CSS",
        heading2: "FEATURES",
        value2: "live web-scraping, debugging tools",
        heading3: "COLLABORATORS",
        value3: "None.",
        heading4: "LEARNINGS",
        value4: "Error handling on web scraping needs to consider slow or non-responsive web pages.",
    },
    {
        title: "Other projects",
        information: "Other projects I have completed using a range of tools can be viewed on my GitHub profile.",
        fileName: "ChallengesShotBanner.png",
        url: "https://github.com/jamesdiffeycoding/",

        heading1: "TECHNOLOGIES",
        value1: "Python, Flask, Django, GraphQL, Next JS, online databases, local storage, event listeners",
        heading2: "FEATURES",
        value2: "responsiveness, database-connectivity",
        heading3: "COLLABORATORS",
        value3: "A variety.",
        heading4: "LEARNINGS",
        value4: "Every project completed is another repetition. Each leaves me a bit more aware how to approach similar tasks in the future.",
    },
];
    export default recentProjectsData