const recentProjectsData = [
    {
        title: "Solar Energy",
        information: "'Awesun' Solar Energy Visualiser displays the latest UK solar energy generation statistics in half-hourly increments. Peak production statistics are included for comparison, and a responsive animation to represent the strength of the sun at different times brings interactivity.",
        fileName: "AwesunShotBanner.png",
        url: "https://awesun-solar-visualiser.vercel.app/",

        heading1: "TECHNOLOGIES",
        value1: "React, Next JS, TypeScript, Fetch API, CSS Animations, Tailwind",
        heading2: "FEATURES",
        value2: "responsiveness, live updates, animations, daily/monthly/yearly views",
        heading3: "COLLABORATORS",
        value3: "Built in a team of 3 with GitHub used for version control with regular feedback sessions, retrospectives and code-reviews.",
        heading4: "LEARNINGS",
        value4: "humility!",
    },
    {
        title: "Mathemagical",
        information: "Mathemagical animates beautiful equations, and provides a 'make-your-own-animation' tool.",
        fileName: "MathemagicalShot3.png",
        url: "https://mathemagical.vercel.app/",

        heading1: "TECHNOLOGIES",
        value1: "React, TypeScript, HTML canvas",
        heading2: "FEATURES",
        value2: "responsiveness, fast rendering, create-your-own-animation",
        heading3: "COLLABORATORS",
        value3: "None.",
        heading4: "LEARNINGS",
        value4: "There are many ways to code the same thing, and often pre-made tools which can help (such as HTML canvas) are already available online.",
    },
    {
        title: "Ruby on Rails CRUD Dex",
        information: "This application provides a Pokedex App with create, read, update and delete functionality. I challenged myself to build something using Ruby on Rails and this was my first project.",
        fileName: "RubyDexShotBannerShort.png",
        url: "https://rubyonrails-pokedex.onrender.com/pokemonsters",

        heading1: "TECHNOLOGIES",
        value1: "Ruby on Rails, CSS",
        heading2: "FEATURES",
        value2: "a modifiable database, default values, and create, read, update, delete functionality",
        heading3: "COLLABORATORS",
        value3: "None.",
        heading4: "LEARNINGS",
        value4: "Although setting up Ruby on Rails can be time-consuming, Ruby on Rails offers some command line tools that can siginificantly aid database-setup.",
    },
    {
        title: "Positive Homeless Shelter Database",
        information: "The application helps staff quickly record information about their service users while out in the streets or back in the shelter. It aims to help improve both service staff and service user experiences.",
        fileName: "ShelterShotsBanner.png",
        url: "https://secure-nextjs-homeless-shelter-database.vercel.app/",
        heading1: "TECHNOLOGIES",
        value1: "Next JS, Supabase (authentication), Jest (testing), SQL",
        heading2: "FEATURES",
        value2: "authentication, authorisation, testing, database-connectivity",
        heading3: "COLLABORATORS",
        value3: "Built in a team of 6 with GitHub used for version control with regular feedback sessions, retrospectives and code-reviews.",
        heading4: "LEARNINGS",
        value4: "Don't spent excessive time optimising for use cases you may never need.",
    },
    {
        title: "Deployment Debugger",
        information: "This application allows me to check all of my deployments statuses (and prevent any from spinning down with activity) by visiting a single site. Python, Flask and Beautiful Soup were used to scrape my sites for their html content, and the site itself displays whether the url request was valid, and whether the html response to the request was as expected.",
        fileName: "DeploymentsDashboardShot2.png",
        url: "https://jamesdiffeycoding-pythonlivedashboard.vercel.app/",

        heading1: "TECHNOLOGIES",
        value1: "Python, Flask, BeautifulSoup (web scraper) HTML, CSS",
        heading2: "FEATURES",
        value2: "live web-scraping, debugging tools",
        heading3: "COLLABORATORS",
        value3: "None.",
        heading4: "LEARNINGS",
        value4: "Error handling on web scraping needs to consider slow or non-responsive web pages.",
    },
    {
        title: "Other projects",
        information: "Other projects I have completed using a range of tools can be viewed on my GitHub profile.",
        fileName: "ChallengesShotBanner.png",
        url: "https://github.com/jamesdiffeycoding/",

        heading1: "TECHNOLOGIES",
        value1: "Python, Flask, Django, GraphQL, Next JS, online databases, local storage, event listeners",
        heading2: "FEATURES",
        value2: "responsiveness, database-connectivity",
        heading3: "COLLABORATORS",
        value3: "A variety.",
        heading4: "LEARNINGS",
        value4: "Every project completed is another repetition. Each leaves me with more perspective on how best to approach development in the future.",
    },
];
    export default recentProjectsData